name: Go CI on Windows

on:
  push:
    branches:
      - main # or your main development branch

jobs:
  build:
    runs-on: windows-latest # Specify a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' # Specify the Go version you want to use

      - name: Build Go application
        run: cd hello && go build -o hello-world.exe main.go

      - name: Run Go application
        run: cd hello && .\hello-world.exe